version: "3.8"

services:
  postgres-go-fiber:
    container_name: postgres-go-fiber
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-fiber-api:
    container_name: go
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/go/src/api
    depends_on:
      postgres-go-fiber:
        condition: service_healthy # waiting until heathcheck of postgres is good
    ports:
      - "3001:3001"